[package]
name = "sdp"
version = "0.1.0"
edition = "2021"

[dependencies]
abstractions = { version = "0.1.0", path = "../../abstraction" }
byteorder = "1.5.0"
chrono = "0.4.38"
http = "1.1.0"
timespan = "0.2.1"
