[package]
name = "rtcp"
version = "0.1.0"
edition = "2021"

[dependencies]
abstractions = { version = "0.1.0", path = "../../abstraction" }
byteorder = "1.4"
num-derive = "0.4.2"
num-traits = "0.2.19"
